# Generated by Django 3.1.2 on 2020-12-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20201228_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
