# Generated by Django 3.1.2 on 2020-12-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_category_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
